- cron: "*/30 * * * * *" # Cron expression
  source:
    type: "s3" # At the moment S3 is the valid source type
    config:
      accessKey: "access_key" # AWS access key
      secretKey: "secret_key" # AWS secret key
      region: "region" # AWS region
      bucket: "bucket" # AWS S3 bucket
  target:
    type: "filesystem" # At the moment filesystem is the valid target type
    config:
      outdir: "./out" ##Better not to change the outdir. Docker volume has been created with this directory. If you change it you can only view the files inside docker container
